export enum FieldCategoryEnum {
    TEXT = 'TEXT',
    NUMBER = 'NUMBER',
    PERCENTAGE = 'PERCENTAGE',
    DATE = 'DATE',
    LIST = 'LIST',
    NUMBER_UNIT_PAIR = 'NUMBER_UNIT_PAIR',
    COUNTRY_PROVINCE_DISTRICT = 'COUNTRY_PROVINCE_DISTRICT',
    ATTACHMENTS = 'ATTACHMENTS'
}
