backend:
  replicaCount: 3
  image:
    repository: registry.gitlab.com/diginexhk/usdol/usdol-backend
    tag: "{{ .Env.CI_PIPELINE_ID }}"
    pullSecrets:
      - usdol-backend-uat-dockercfg

  dockercfg:
    enabled: true
    image:
      pullSecret:
        registry: registry.gitlab.com
        username: josiah.choi_diginex
        password: {{ .Env.IMAGE_REPOSITORY_PASSWORD }}

  deployment:
    enabled: true
  service:
    enabled: true
    type: ClusterIP
    ports:
      default:
        internal: 3000
        external: 3000
  resources:
    limits:
      cpu: 2
      memory: 2048Mi
    requests:
      cpu: 20m
      memory: 64Mi
  virtualService:
    enabled: true
    hosts:
      - 'globaltrace-api.uat.dgnx.io'
    gateways:
      - default/ingressgateway-uat-dgnx-io
    routes:
      default:
        destination:
          host: usdol-backend-uat-backend
          port: 3000
  env:
    DATABASE_CONNECT: postgres
    DATABASE_HOST: usdol-infra-uat-postgresql
    DATABASE_PORT: 5432
    DATABASE_USER: postgres
    DATABASE_PASSWORD: postgres
    DATABASE_NAME: usdol
    REDIS_HOST: usdol-infra-uat-redis-master
    APP_ENV: uat
    APP_PORT: 3000
    JWT_SECRET: diginex
    JWT_EXPIRE: 3d
    JWT_REFRESH_SECRET: diginex-secret-refresh-token
    JWT_REFRESH_EXPIRE: 7d
    WEB_URL: https://globaltrace.uat.dgnx.io
    BACKEND_URL: https://globaltrace-api.uat.dgnx.io
    MAILER_URL: smtp://mail.mail-uat.svc.cluster.local:587?auth=false
    MAIL_SEND_FROM: "Diginex USDOL <usdol-test@uat.dgnx.io>"
    WHITELIST_DOMAINS: localhost:*,0.0.0.0:*,127.0.0.1:*,*.dgnx.io
    CONTACT_MAIL: support@diginex-usdol.com
    THROTTLE_LIMIT: 1000
    S3_ACCOUNT_NAME: {{ .Env.S3_ACCOUNT_NAME }}
    S3_ACCOUNT_KEY: {{ .Env.S3_ACCOUNT_KEY }}
    S3_BLOB_CONTAINER: usdol-dev
    BRANCH_DYNAMIC_LINK_API_KEY: {{ .Env.BRANCH_DYNAMIC_LINK_API_KEY }}
    RAPID_API_KEY: {{ .Env.RAPID_API_KEY }}
    RAPID_API_GEODB_HOST: wft-geo-db.p.rapidapi.com
    RAPID_API_GEODB_BASE_URL: https://wft-geo-db.p.rapidapi.com/v1/geo
    RAPID_MAX_PAGE_LIMIT: 100
    RAPID_MAX_REQUEST_PER_SECOND: 10
    OPEN_APPAREL_REGISTRY_API_KEY: {{ .Env.OPEN_APPAREL_REGISTRY_API_KEY }}
    OPEN_APPAREL_REGISTRY_BASE_URL: https://opensupplyhub.org
    GOOGLE_MAPS_API_KEY: {{ .Env.GOOGLE_MAPS_API_KEY }}
    WEB_2_PDF_API_URL: https://web2pdf-api.dev3.dgnx.io
    WEB_2_PDF_API_KEY: {{ .Env.WEB_2_PDF_API_KEY }}
    NODE_ENV: uat
