export const CONVERSION_RATIO_UNIT_TO_KG = 16000;
export const CONVERSION_RATIO_LBS_TO_KG = 0.453592;

export const TOTAL_WEIGHT_NUMERIC_PRECISION = 14;
export const TOTAL_WEIGHT_NUMERIC_SCALE = 2;

export const LINT_COTTON_CONVERSION_RATIO = 0.35;
