export enum UserRoleEnum {
    SUPER_ADMIN = 'SUPER_ADMIN',
    ADMIN = 'ADMIN',
    FARM_GROUP = 'FARM_GROUP',
    GINNER = 'GINNER',
    SPINNER = 'SPINNER',
    BROKER = 'BROKER',
    TRANSPORTER = 'TRANSPORTER',
    MILL = 'MILL',
    BRAND = 'BRAND',
    AUDITOR = 'AUDITOR',
    FARM_MONITOR = 'FARM_MONITOR',
    FARM_MONITOR_WEB = 'FARM_MONITOR_WEB',
    FINAL_PRODUCT_ASSEMBLY = 'FINAL_PRODUCT_ASSEMBLY',
    FARM = 'FARM'
}
