export enum ErrorTypeEnum {
    JOI = 1,
    DUPLICATED_EMAIL_IN_FILE_TEMPLATE = 2,
    EXISTED_FACILITY_EMAIL_IN_DATABASE = 3,
    DUPLICATED_ID_IN_FARM_TEMPLATE = 4,
    INVALID_FARM_ID = 5,
    INVALID_COORDINATE = 6,
    EXISTED_FACILITY_OARID_IN_DATABASE = 7,
    EXISTED_FACILITY_IN_DATABASE = 8,
    SAQ_HAS_NOT_COMPLETE = 9
}
